### ISSUE TITLE
Only Linux?

### ISSUE THREAD

**Issue by ghost** [krambambuli/mailclient#1]
?

**Comment by cmkrafft** [comment]
At least it was developed on Linux. As far as I know everything, except for the icons (e.g. read/unread mail and so on), does also work on Windows or whereever you might want to run it.

**Comment by ghost** [comment]
@krambambuli We will have to try to compile under Windows =)

**Comment by cmkrafft** [comment]
I assume that it will work, but if there are any problems, feel free to ask :-)
